### ISSUE TITLE
Update build pipeline to Jenkins as Code

### ISSUE THREAD

**Issue by MichaelMadsen** [Praqma/codesonar-plugin#11]
We're moving to Jenkins as Code at https://jenkins.praqma.cloud/
We could move the current DSL directly, but we would like to modernise. Therefore the current DSL should
 be converted to declarative pipeline script.

**Comment by MichaelMadsen** [comment]
Pipeline ready in branch https://github.com/Praqma/codesonar-plugin/tree/11-Update-build-pipeline-to-Jenkins-as-Code.

This replaces the current DSL, so shouldn't be merged in until a release has been manually tested and we know for sure it can take over from old jobs.
The final 2 steps of the pipeline make a full release of the Jenkins plugin, and are therefore disabled until a manual test can be done with @Ordojan, making sure that these last steps work.

**Comment by buep** [comment]
Why are we migrating job DSL to pipeline? There is no strategy of using only pipeline... and we need to convert at lot of other jobs first before we start switching already scripted jobs to another type of scripting.

In general going forward, we will not convert from one type to another.. but only script what is missing.

**Comment by buep** [comment]
Done by other issues, jobs can be found here: https://jenkins.praqma.cloud/job/Codesonar%20Jenkins%20Plugin/

Jobs comes from https://github.com/Praqma/praqma-jenkins/blob/master/dockerizeit/master/jenkins.properties and these files: https://github.com/Praqma/codesonar-plugin/tree/master/jenkins-pipeline
