### ISSUE TITLE
Code Sonar Handover

### ISSUE THREAD

**Issue by groenborg** [Praqma/codesonar-plugin#12]
This is the notes from the handover session specifying how to build, test and run the codesonar plugin

**Comment by groenborg** [comment]
### Maven Commands for running builds
clean and rebuild package
`mvn clean package`

Creates a local Jenkins instance, incapsulated in the work folder
`mvn clean hpi:run`

**Comment by groenborg** [comment]
### Releasing a new version of codesonar plugin
`mvn release:prepare`
this is done by the pipeline

**Comment by buep** [comment]
Hand-over was done so closing it
