### ISSUE TITLE
Setup Jenkins V2.60 with codesonar plugin

### ISSUE THREAD

**Issue by kryptag** [Praqma/codesonar-plugin#17]
Setup the right env that matches the description of the bug report.

1. Try to se if CodeSonar plugin is compatible with this version
2. Run code analysis of CodeSonar plugin source code

**Comment by buep** [comment]
How is this relevant?

**Comment by buep** [comment]
We the test setup delivered in #39 and the tests running in #43 we're using a much newer Jenkins and it seems to work. So closing this file.
