### ISSUE TITLE
Look into Memory problem when analyzing multimillion line project

### ISSUE THREAD

**Issue by kryptag** [Praqma/codesonar-plugin#22]
"the memory requirements of the plugin on large analyses are impractical and the user had given up on the plugin and instead set up Jenkins to run codesonar manually.  The user suspected a memory leak, however I suspect it may simply be an issue where it attempts to keep too much data in memory at once."

**Comment by buep** [comment]
I contacted Grammatech related big project testing approaches.

**Comment by kryptag** [comment]
![image](https://user-images.githubusercontent.com/11290150/34874625-1e02a730-f79a-11e7-9eb1-0f1fa2e582d4.png)

in this picture we can see the memory usage of all the objects, the interesting part is the warnings object. we have 12910 instances that where made, and the collected memory usage of the objects are 806Kb. These all have the size of 0.0624Kb, which makes it a linear growth and this will cause problems at a certain size or amount of warnings. The question is if it's feasible to try and solve the issue or we should tackle it in a different way.

**Comment by buep** [comment]
Proposed tool from @kryptag http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html

**Comment by buep** [comment]
We're running such tests with test setup available after closing #39 and with analysis from #43 - will close this old issue.
