### ISSUE TITLE
Reuse authenticated session when fetching analysis results

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/codesonar-plugin#50]
>If CodeSonar is set to restrict access to analysis results so 
>Anonymous cannot see results, and an appropriate user name and password 
>is provided to the plugin, the plugin still fails to collect the 
>information. Based on the http requests made, the login attempt happens 
>and succeeds, but the request for results doesn't use that session and 
>instead starts a new anonymous session. When the anonymous session fails 
>to get results, the named session disconnects. This looks like a need to 
>keep track of the session from the login for other requests.

**Comment by MadsNielsen** [comment]
@OEHC can you add screenshots of the permissions you've configured in the hub during this proces? I.e showing what your settings are when we fail, and showing settings when we succeed?

**Comment by OEHC** [comment]
The default permissions, which the first run were executed under:
![screenshot from 2018-10-18 10-18-41](https://user-images.githubusercontent.com/8385539/47142706-d04d9080-d2c3-11e8-84f4-b7aee2d908b3.png)

The permissions are revoked using this `Restrict Permissions` button from Settings -> User Administration -> Security Dashboard
![screenshot from 2018-10-18 10-18-56](https://user-images.githubusercontent.com/8385539/47142708-d04d9080-d2c3-11e8-98fe-c22d08909820.png)

Here are the permissions after being restricted.
![screenshot from 2018-10-18 10-19-23](https://user-images.githubusercontent.com/8385539/47142709-d04d9080-d2c3-11e8-8f77-9484ff13b2ae.png)

I can make the job run using both of these configurations, by using `Administrator`'s login details in the pipeline

**Comment by PaulVanNiekerk** [comment]
CodeSonar Plug-in version is 2.0.7 (latest).

Logging from the Jenkins job (Running on Jenkins3, CS and hub version 4.5p3.20180706):
 
ERROR: Step ‘Codesonar’ failed: [CodeSonar] Error on url: http://127.0.0.1:7340/analysis/1634.xml?filter=2
[CodeSonar] Message is: FORBIDDEN
Finished: FAILURE
 
The URL is fine; localhost is OK as Jenkins and the hub are on the same machine.
Two interesting CodeSonar log files  are traffic.txt and userlog.txt.

In traffic.txt we found:
[91018] 2018-07-12 17:08:18,307 - 127.0.0.1:**41680**: POST /sign_in.html HTTP/1.1
[91018] 2018-07-12 17:08:18,822 - 127.0.0.1:41680: HTTP/1.1 200 OK
[91836] 2018-07-12 17:08:18,974 - 127.0.0.1:**41710**: GET /analysis/1634.xml?filter=2 HTTP/1.1
[91836] 2018-07-12 17:08:19,023 - 127.0.0.1:41710: HTTP/1.1 403 FORBIDDEN
 
Note that the POST and the GET are using different ports, so are not part of the same session!?
In userlog.txt we found:
 
[91018] 2018-07-12 17:08:18,812: User Signed In
  Address: 127.0.0.1:**41680**
  Request: POST /sign_in.html HTTP/1.1
  Username: jenkins
  
[91836] 2018-07-12 17:08:19,007: Error
  Address: 127.0.0.1:**41710**
  Request: GET /analysis/1634.xml?filter=2 HTTP/1.1
  Message: Anonymous does not have the "Analysis Read" permission for Analysis 1634.
  
The last message indicates that this is indeed seen as a separate session for user Anonynous.

Could you maybe check the two files in your test setup?

**Comment by PaulVanNiekerk** [comment]
Note that the issue is not performing a codesonar build with specific credentials, that works OK. The issue is using the plug-in with specific credentials: The plug-in fetches the results using the above URL, giving the above error message, and causing the above logging in CodeSonar.

**Comment by PaulVanNiekerk** [comment]
These are my steps to reproduce.
Since the analysis is already done succesfully, using ID 1634, the shell script in the Jenkins jobs can be reduced to:

```
#!/bin/bash -ex
env
id
echo user name is ${PARAM_CS_USER}
echo codesonar: http://127.0.0.1:7340/analysis/1634.html
exit 0
```

This works fine when 'Anyone' has enough global permissions.
As soon as I revoke all global permissions for 'Anyone', this job starts failing with this message:

```
ERROR: Step ‘Codesonar’ failed: [CodeSonar] Error on url: http://127.0.0.1:7340/analysis/1634.xml?filter=2
[CodeSonar] Message is: FORBIDDEN
Finished: FAILURE
```

In the job I have these settings:
![image](https://user-images.githubusercontent.com/44370431/47350487-44b67400-d6b6-11e8-890d-b14304f26acf.png)

![image](https://user-images.githubusercontent.com/44370431/47350572-6e6f9b00-d6b6-11e8-9a96-7da44a825bbe.png)

In the CS logging we see that the login is OK (order is not chronological in the log file):
```
[13988] 2018-10-23 11:10:35,254: Error
  Address: 127.0.0.1:40736
  Request: GET /analysis/1634.xml?filter=2 HTTP/1.1
  Message: Anonymous does not have the "Analysis Read" permission for Analysis 1634.
  
[13970] 2018-10-23 11:10:35,202: User Signed In
  Address: 127.0.0.1:54476
  Request: POST /sign_in.html HTTP/1.1
  Username: jenkins

```

**Comment by PaulVanNiekerk** [comment]
Looking a bit further, the 'pstree' command shows that on our system the original 'cshub' process spawned many cshub child processes:

$ pstree -p -a -l 13954
cshub,13954 start /data/codesonar
  ├─cshub,13970 start /data/codesonar
  ├─cshub,13973 start /data/codesonar
  ├─cshub,13976 start /data/codesonar
  ├─cshub,13979 start /data/codesonar
  ├─cshub,13982 start /data/codesonar
  ├─cshub,13985 start /data/codesonar
  ├─cshub,13988 start /data/codesonar
  ├─cshub,13991 start /data/codesonar
  ├─cshub,13994 start /data/codesonar
  ├─cshub,13997 start /data/codesonar
  ├─cshub,14001 start /data/codesonar
  ├─cshub,14037 start /data/codesonar
  ├─cshub,14094 start /data/codesonar
  ├─cshub,14118 start /data/codesonar
  ├─cshub,14131 start /data/codesonar
  ├─cshub,19026 start /data/codesonar
  ├─cshub,70016 start /data/codesonar
  ├─cshub,73735 start /data/codesonar
  └─postgres,13956 -D /data/codesonar/pgdata
      ├─postgres,13957                                                                            
      ├─postgres,13959                                                                      
      ├─postgres,13960                                                                            
      ├─postgres,13961                                                                        
      ├─postgres,13962                                                               
...

The numbers are PIDs. From this it can be seen that the login (POST) was handled by the child with PID 13970, and the GET was handled by a different child with PID 13988. 

From your data I see that the login and the GET were handled by the *same* process. Could you try reproducing again in a configuration with many such cshub child processes?

**Comment by OEHC** [comment]
I will try to upgrade my Jenkins version to match your version, and try to spawn more cshub processes.

**Comment by OEHC** [comment]
I tried to make [cshub spawn a bunch of childs](https://user-images.githubusercontent.com/8385539/48056771-c3310c80-e1b2-11e8-845e-f694d9c096a6.png). I ran a big job with a lot of analysis to do, and ran a couple of small jobs parallel. Each time a job finished, Jenkins authenticated using the credentials provided, and fetched the results. It was not always the same cshub child Jenkins authenticated against, but when it authenticated using some child, it fetched from the same and logged out of the session afterwards.
Is your Jenkins job running on the Jenkins master or on some slave? I have no slaves configured. I think some difference in our setup cause this behavior, since we both get consistent but different results.

**Comment by OEHC** [comment]
I will try to get a license for cshub v. 4.5p3, to match your version, and try testing with Jenkins slaves.

**Comment by PaulVanNiekerk** [comment]
We're currently not using any Jenkins slaves, although we might want to do that later.
Regarding the version of the plugin, are you testing with the latest released version, or with the latest in the repository? We're using 2.0.7 as released.

**Comment by OEHC** [comment]
I have now tested with CodeSonar v. 5.0p0.20180811. Unfortunately I still don't get any `403 FORBIDDEN` messages, and the graphs in Jenkins get the data points from CodeSonar just fine.
