### ISSUE TITLE
Feature: Allow user to set absolute threshold of max X warnings with a score of Y or higher

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/codesonar-plugin#51]
>As a user would like to be able to set a score threshold for what 
>is reported, and have a Jenkins failure option that is based on absolute 
>counts at or above the threshold. So, for example, they might choose to 
>set the threshold at a score of 56. This would count all the CodeSonar 
>warnings that have the red marker at the far left hand side of the 
>warning table. Then they would like the Jenkins run to fail if the count 
>of these issues is greater than a specified absolute value. This is not 
>a comparison to the count from the previous run, but an absolute value. 
>For example, 20. Then, if this is feature is implemented the Jenkins 
>run would list as a failure if there are more than 20 warnings with a 
>score of 56 or higher. Warnings with lower scores are not a concern for 
>this scenario.

**Comment by OEHC** [comment]
This has been manually tested to work. If **more** then `Maximum warnings` with score **at least** `Rank of warnings` are reported, the job will get status `Mark build as`. Else the plugin will mark the build successful.
